### ISSUE TITLE
extend POST /dgci/wallet/claim for multiple claim

### ISSUE THREAD

**Issue by a-trzewik** [eu-digital-green-certificates/dgca-issuance-service#37]
Need to be specified first
unclear how this new TAN should be generated

**Comment by SchulzeStTSI** [comment]
The patch method was forseen for linking multiple public keys (multiple devices) to one certificate, because the certicate relates to just one person, which can not handle multiple devices in the same time. The POST method will be enhanced to ensure that the certificate can be transfered to a other device. This function is therefore set to out of scope for the moment.

**Comment by a-trzewik** [comment]
PATH /dgci/wallet/claim is not suported
POST /dgci/wallet/claim return new tan (which not expires) and can be used for new claim
