### ISSUE TITLE
Valid Certificate Produced for Positive Covid Test Results

### ISSUE THREAD

**Issue by psavva** [eu-digital-green-certificates/dgca-issuance-service#54]
## Describe the bug

When generating a DGC, one option is to input the Positive Result of a Covid Test. 
Hence, the person was tested Positive for Covid.

I am able to proceed to produce the DGC, and get a Green and Valid verification.

## Expected behaviour

Digital Green certificate should not be issued to anyone with a Positive Covid Test Result.

## Steps to reproduce the issue

See Screenshot 

![PositiveCovidDGC](https://user-images.githubusercontent.com/1454758/118111662-af526b00-b3ec-11eb-9259-378b232fae44.PNG)

## Possible Fix

Implement Validation as to which values in the value sets should produce a DGC and which should not.

**Comment by SchulzeStTSI** [comment]
@psavva Thanks for the hint. Currently is the assumption that this can be issued, but the verifier apps will report "invalid" if you scan a certificate issued with "detected" value.

**Comment by psavva** [comment]
The verifier app on Android that I have at least tested passed validation

**Comment by SchulzeStTSI** [comment]
@psavva In IOS it's already working. In Android is this feature not yet working. https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/issues/32

**Comment by psavva** [comment]
This was not working as of when I raised this ticket.

**Comment by a-trzewik** [comment]
The ticket was widly discussed. The final decission is that the positive test can be issued (signed) and  it is task of validation app to revoke it (show red).

Consider that the issuence-service (this module) do not have insight into certificate data. It signs only hashed data. All certificate data never leave web front-end, they are not transfered to issuance-service. So this functonality can not be modified in dgca-issuance-service but only in dgca-issuance-web. The issuance only says something about data integrity but not provide information about if the certificate itself is valid. The validation itself can be much more complex. For example some test can be considered as invalid because the test compound was found defect later.
