### ISSUE TITLE
Support for last releases of hcert-kotlin

### ISSUE THREAD

**Issue by JonathanIN** [eu-digital-green-certificates/dgca-issuance-service#86]
## Your Question
Hi, 
When looking at the pom.xml file, it appears that this release is based on the release 1.0.1 of hcert-kotlin.
However there has been several releases of hcert-kotlin since the 1.0.1, especially the 1.1.1 which is compatible with the JSON schema 1.3.0 (field tc not mandatory). 
We tried to change the version of hcert-kotlin in the pom.xml file to a more recent one but we were not able to compile the release. 

Do you plan to deliver a new release compatible with the latest hcert-kotlin version? If not, how can we support JSON schema 1.3.0 using this release of the dgca-issuance-service?

Thank for your feeedback,
Regards,

* Source File:
* Line(s):
* Question:

**Comment by a-trzewik** [comment]
Indeed hcert kotlin lib is used only for so called backend issuing and test API. This interfaces are regularly disabled (per spring configuration see application.yml)
In default setting the dcc is handled by frontend see https://github.com/eu-digital-green-certificates/dgca-issuance-web
It means the 1.3.0 is handled properly if you use it with web frontend.
Unfortunately the hcert updates causes many affords because its public api changes a lot from version to version.
